### ISSUE TITLE
 No podspec found for `sim_data`

### ISSUE THREAD

**Issue by muarachmann** [vkammerer/sim_data#1]
I get this when trying to run on ios. Any help, on how to go about this?

```
Analyzing dependencies
[!] No podspec found for `sim_data` in `.symlinks/plugins/sim_data/ios`

[!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

**Comment by vkammerer** [comment]
Hello, as the README states, this plugin only supports Android for now.
If you want to open a PR that adds support for iOS too, I would be happy to review it.

**Comment by UjuziKilimoDevs** [comment]
Can I test this using an emulator or it has to be on a physical device?

**Comment by emkaburu** [comment]
Can I test this using an emulator or it has to be on a physical device?

**Comment by vkammerer** [comment]
@emkaburu I don't know of any emulator that would handle a USSD request so it has to be on a physical device
